// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: 'info'}],
  api: [{type: 'autogenerated', dirName: 'api'}],
};

module.exports = sidebars;
